---
default_install_hook_types:
  - pre-commit
  - commit-msg

exclude: '(postCommand.sh|docker/legacy/|vault|dist|plugins|creds|jinja|jinja2|j2|groovy|sql|csv|sln)'

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      # - id: check-added-large-files
      #   args: ['--maxkb=1524']
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.25
    hooks:
      - id: shellcheck

  # https://github.com/compilerla/conventional-pre-commit
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
